language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
before_install:
  - nvm install stable
  - nvm use stable
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - cd server
  - dotnet restore
  - cd ../server.test
  - dotnet restore
  - cd ..
  - yarn install
script:
  - dotnet test
  - yarn test
cache:
  yarn: true