language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
before_install:
  - nvm install stable
  - nvm use stable
before_script:
  - cd server
  - dotnet restore
  - cd ../server.test
  - dotnet restore
  - cd ..
  - yarn install
script:
  - cd server.test
  - dotnet test
  - cd ..
  - yarn test
cache:
  yarn: true