language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
before_install:
  - nvm install stable
  - nvm use stable
before_script:
  - cd Diporto
  - dotnet restore
  - cd ../DiportoTests
  - dotnet restore
  - cd ../Diporto
  - yarn install
script:
  - cd ../Diporto
  - cp appsettings.Travis.json appsettings.Development.json
  - dotnet ef database update
  - cd ../DiportoTests
  - dotnet test
  - cd ..
  - yarn test
cache:
  yarn: true
services:
  - postgresql
env:
  - ASPNETCORE_ENVIRONMENT=Development
